name: images

on:
  push:
    branches:
      - '**'
  pull_request:
    paths:
      - '**'
      - '!doc/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '~1.16'
      - run: docker build . -f upstream-opm-builder.Dockerfile
